server:
  port:
spring:
  application:
    name: rest-data
  datasource:
    url:
    username:
    password:
    hikari:
      idle-timeout: 15000
      max-lifetime: 35000
      validation-timeout: 300000
      connection-timeout: 300000
      connection-test-query: SELECT 1
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        default_schema:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
          jwk-set-uri:
      client:
        registration:
          keycloak:
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri:
            user-name-attribute: preferred_username
  data:
    rest:
      detection-strategy: annotated
management:
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
      probes:
        enabled: true
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true
    info:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.security: INFO
